/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://grihdnhlrfb7llteu2rgxawgzq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ydimesmnqndi7ec2qy3xao3wse",
    "aws_cognito_identity_pool_id": "us-west-2:20516bd4-7af7-4928-9462-e48384fa03e7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dIpf1cImA",
    "aws_user_pools_web_client_id": "7qglalu6lj38j5eve7vp7cakeu",
    "oauth": {},
    "aws_user_files_s3_bucket": "postagramb545f858330d4209b8e0e3ce046e93d5182440-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
